### ISSUE TITLE
[Feature] Create Application Resource Mapping for CronJob by default

### ISSUE THREAD

**Issue by baijum** [kubepreset/kubepreset#14]
## 🚀 Describe the Feature

[CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) is Non-PodSpec-able builtin resource.
Creating Application Resource Mapping for CronJob by default would be convenient.

## 💡 Describe the Solution You'd Like

During the installation time, create `ClusterApplicationResourceMapping` resource for [CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) with this configuration:

```
apiVersion: service.binding/v1alpha2
kind: ClusterApplicationResourceMapping
metadata:
 name:  cronjobs.batch
spec:
  versions:
  - version: "*"
    envs:
    - .spec.jobTemplate.spec.template.spec.containers[*].env
    - .spec.jobTemplate.spec.template.spec.initContainers[*].env
    volumeMounts:
    - .spec.jobTemplate.spec.template.spec.containers[*].volumeMounts
    - .spec.jobTemplate.spec.template.spec.initContainers[*].volumeMounts
    volumes: .spec.jobTemplate.spec.template.spec.volumes
```

## 🚶 Describe Alternatives You've Considered

If not this approach, it should be documented.

## ➕ Additional Context

Similar resources be created or at least documented for popular Non-PodSpec-able resources.
