### ISSUE TITLE
ClusterRole rules has all permissions for all resources in all API groups

### ISSUE THREAD

**Issue by baijum** [kubepreset/kubepreset#5]
This is the current [ClusterRole rules](https://github.com/kubepreset/helm-charts/blob/5b456384be60caea96e23db8fe895f3b039fddaa/charts/kubepreset/templates/rbac.yaml#L33)

```
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
```

Instead of this ClusterRole, there should be more specific ClusterRole definitions with limited number of API groups, resources, and verbs.
